# Generated by Django 5.2.6 on 2026-05-19 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connectionspuzzle',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='connectionspuzzle',
            name='date',
        ),
    ]
