# Generated by Django 5.2.6 on 2026-06-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_connectionsdraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionspuzzle',
            name='release_date',
            field=models.DateField(blank=True, help_text='Date this puzzle becomes available to players. Null = queued/unreleased.', null=True),
        ),
    ]
