# Generated by Django 5.2.6 on 2026-06-01 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_connectionspuzzle_release_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuzzleCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('won', models.BooleanField()),
                ('mistakes_made', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='dashboard.connectionspuzzle')),
            ],
            options={
                'ordering': ['-completed_at'],
                'unique_together': {('puzzle', 'session_key')},
            },
        ),
    ]
