# Generated by Django 5.2.6 on 2025-12-18 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=200, unique=True)),
                ('logic_code', models.CharField(help_text="This code must match the key in your validation logic (e.g., 'title_has_color').", max_length=100, unique=True)),
                ('description', models.CharField(blank=True, help_text="Explanation that appears when user hovers/clicks (e.g., 'Must have fewer than 200 pages according to Google Books').", max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this category from future puzzles.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['display_name'],
            },
        ),
    ]
