# Generated by Django 5.2.6 on 2025-12-25 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPuzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('col_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.category')),
                ('col_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.category')),
                ('col_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.category')),
                ('row_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.category')),
                ('row_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.category')),
                ('row_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.category')),
            ],
        ),
    ]
